name: Deploy Jekyll with GitHub Actions

on:
  push:
    branches:
      - main  # Passe an, falls du einen anderen Branch nutzt

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
     group: jekyll-deploy
     cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Jupyter
        run: pip install jupyter
      
      - name: Clean old site
        run: rm -rf _site

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
